#!/bin/sh
[ -f /etc/odbc.ini ] && mv /etc/odbc.ini /etc/odbc.ini.bak
[ -f /etc/odbcinst.ini ] && mv /etc/odbcinst.ini /etc/odbcinst.ini.bak

cp ./test/odbc.ini /etc/
cp ./test/odbcinst.ini /etc/

[ -f /etc/init.d/mysqld ] && /etc/init.d/mysqld restart
[ -f /lib/systemd/system/mysqld.service ] && systemctl restart mysqld
export TEST_DSN=myodbc5w

result="`pwd`/result.log"
>$result
cd test
for i in `ls` ; do
	[ -x ./${i} ] && echo "./${i}" >>$result
	[ -x ./${i} ] && ./${i}| tee -a $result| grep -e "ok"|sed -e "s/^ok/PASS:/" -e "s/^not ok/FAIL:/"
done

rm /etc/odbc.ini  /etc/odbcinst.ini
[ -f /etc/odbc.ini.bak ] && mv /etc/odbc.ini.bak /etc/odbc.ini
[ -f /etc/odbcinst.ini.bak ] && mv /etc/odbcinst.ini.bak /etc/odbcinst.ini
